### ISSUE TITLE
[Expert] Some Receipts are missing

### ISSUE THREAD

**Issue by Hodel1** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#196]
Hi,
i'm playing right now that IER Pack in expert mode. I found some too cheap receipts, that are in IE1.7.10 harder:

- Hopper - with iron plates instead of ingots
- Mega Torch is orginal receipt, see Magnum Torch in Infinity Evolved - that was much harder. I know in 1.12.2 there is no QED, but you can use for example the laser/injection.
- Wooden Hopper are not available on 1.7.10 - you can deactivate them or replace that wood through treated wood
- Water Wheels are heavy cheap! I'm pretty sure, in 1.7.10 is the "Kinetic Dynamo" much harder, i remember of steel and much electrum so maybe instead that Copper Coil Block in receipt, it was replaced i think with Electrum Coil Block. There i remember, we can craft only 2 instead of 4 coils.

When you can look in that and change that receipts, that would be nice :)

Good Bye, thanks

**Comment by saovenn** [comment]
Thanks for your feedback.

I'll compare the recipes within the next few days and adjust them 👍

**Comment by SirPrimrose** [comment]
There is another recipe that me and my friends have found that I believe was originally disabled in FTB Infinity Evolved: Expert. This is the golden bag of holding from Extra Utils, though for what reason I cannot say. There is a known item dupe bug with it ([bug link](https://github.com/rwtema/extrautilities_old_issues/issues/1800)) and it is incredibly powerful, allowing near infinite inventory space by crafting multiple bags and storing them inside of each other. At the least, this recipe could certainly be made more expensive, though how expensive I do not know, since the recipe was just disabled in the original pack. 

The "woven" versions of backpacks from Forestry require silk wisps, making you go through some level of Forestry before obtaining larger backpacks. In my opinion, the golden bag of holding is far better and cheaper than these Forestry backpacks, so the GBoH should at least as expensive as these bags, if not more.

**Comment by Hodel1** [comment]
The IC2 Cutting Machine outputs only 2 Copper Cables per Copper Plate instead of 3

**Comment by Hodel1** [comment]
The IC2 Cutting Machine has generated 2 Item Casing on 1.7.10 or not? there comes only 1 per plate

**Comment by SirPrimrose** [comment]
@saovenn Is there a philosophy for this pack? I.e. Preserve as many of the recipes from the FTB Inf:Evolved? I played a lot of the old pack and can compare some of the older 1.7.10 recipes with the ones in the 1.12.2 "Reloaded" pack. 

I don't have much experience with the tweaker scripts but I can try making a PR to replace the recipes as well, or I can just collect the information (in screenshot or table form) and drop it here as comments.

**Comment by Hodel1** [comment]
I've seen that Pull Requests are being Merged. Maybe make one PR per Mod/Receipt maybe.

**Comment by SanderWxD** [comment]
@SirPrimrose We haven't really defined the packs philosophy like this.
But what we have been doing so far is really starting with the original as the base, trying to recreate it as closely as possible and doing little additions and improvements here and there.

For example: a few new addons, (more) quests for normal mode, quest rewards, expert laser recipes with fusion crafting etc.

**Comment by SirPrimrose** [comment]
@SanderWxD I can see how most of that has been implemented. I appreciate a lot of the QoL changes like merging the ingots/blocks/dusts and probably some other ones. 

As far as the suggested recipe changes asked for by @Hodel1, I agree with most of them. Not sure exactly how to handle things that didn't exist in the previous pack (like the bag of holding and wooden hopper), though I wouldn't mind making suggestions/opening a PR with recipes and having a discussion.

**Comment by SanderWxD** [comment]
Please do make suggestions and open PR's with recipes to discuss about. Some new items can be a bit difficult to give an accorate/fitting recipe. As for the golden bag of holding in particular: that one is very buggy on the SpongeForge server I play on. Unsure how that is on singleplayer and other servers. If its buggy everywhere, we wont have to make an expert recipe for it.

**Comment by SanderWxD** [comment]
Fixed in the upcoming update.
