### ISSUE TITLE
BC lasers

### ISSUE THREAD

**Issue by scott3496** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#96]
You can not power BC lasers with ender up or ie cables like you could in the older pack. This breaks the quest line as you need power it with MJ cables only

**Comment by fabrossmann** [comment]
Buildcraft introduced its own energy system.In order to convert RF/EU to MJ, we added the Mod [Energy Converters](https://www.curseforge.com/minecraft/mc-mods/energy-converters). You can also find hints in the questbook quest for the laser and also a entire quest about the mod in the second chapter.
